# Onboarding

Welcome to JRaviLab! We are excited that you are here --- as a student, postdoc, or visiting researcher! We have a number of resources available in this short e-book and on Slack. Please take the time to check these out. As you read them, if something is unclear, please feel free to reach out to the group anytime.

Once you are done with the 'familiarizing' and getting to know the first steps, please send me (JR) a message on Slack. Please bring your questions, thoughts, and feedback to the meeting.

Good luck & welcome aboard! 🎉

# Mission, Expectations, Conduct, Support

-   Mission, expectations, code of conduct
-   [Health, wellness](https://jravilab.github.io/lab_docs/resources.html#health-and-wellness), safety
-   Diversity, accessibility

We value believe in investing in and nurturing scientists as much as the science. We pride ourselves on providing a safe and inclusive space for people across intersectionalities. We are committed to mentoring (postdocs, students, programmers), education and outreach, and personalized professional development. We are passionate about finding ways to increase diversity and retention in STEM and quantitative sciences. If you share our passion, please [reach out to us](//jravilab.github.io/joinus)!

*Links and details to follow.*


# Role-Specific Expectations

## Undergraduates

Welcome to the JRaviLab — we’re excited to have you!
This may be your first research experience, and we understand that the onboarding process can feel overwhelming.
Know that everyone is here to support and guide you as you navigate your research journey.
Chances are, conducting independent research will be much different from your previous academic experiences,
so we have compiled a list of pointers to help you understand your roles and expectations as an undergraduate researcher.

<details>
<summary>Roles and expectations for undergrads</summary>

-   **Be present.** Attend meetings and bring forth your best effort.
-   **Ask for help.** We encourage you to be proactive; ask questions and provide any updates or ideas to our Slack channels.
-   **Strive for growth.** It will be challenging, but we want you to keep trying and to persist – learning is the main goal, and being receptive and open to constructive feedback is a great way to improve.
-   **Give yourself grace.** You’ve earned a spot in our community, and you belong here. Failure is inevitable with the work we’re doing; your work doesn’t define you or your abilities. We’re all here for you!
-   **Stay organized.** Keeping track of your priorities, tasks, and responsibilities will allow you to monitor your progress and make it easier for others to help you. Time management is essential for pacing yourself to achieve your goals.
-   **Collaborate.** We encourage you to present your work and discuss with others frequently. Learn about the projects your labmates are working on, communicate any troubles or issues before they boil (work-related and not), and keep a positive mental attitude!
-   **Own your research.** This is *your* research process, so be sure that you’re putting forth your best work and that you continue to practice scientific reading and writing.
-   **Take advantage of resources.** There are many avenues for learning in research. Here are a few to get you started:
    + [JRaviLab: How to X](https://jravilab.github.io/lab_docs/howto.html)
    + Slack channels
    + [Stack Overflow](https://stackoverflow.com/)
    + [NIH NCBI](https://www.ncbi.nlm.nih.gov/pmc/)
    + Google, [Google Scholar](https://scholar.google.com/)
    + [ChatGPT](https://chat.openai.com/auth/login)
</details>

## Research associates (PRAs)
-   
-   
-   


## Graduate students
-   
-   
-   


## Postdoctoral fellows (Postdocs)

As a postdoctoral researcher, you wear many hats in addition to those of more junior scientists in the lab.

-   A postdoctoral position is a training opportunity -- you are here to learn new skills and expand your scientific boundaries. You are not expected to know everything, but you should be comfortable (and preferably excited!) throwing yourself into new problems and solving them.
-   You are also here to help others learn. Postdocs have considerable experience in many aspects typically involving academia, research, and more. That experience can be very helpful for scientists who are earlier in their own careers. Contribute generously where you can, and make yourself available for ohers in the group. A rising tide lifts all boats.
-   You may work on a number of existing projects across the lab, either leading them or helping each team navigate research obstacles. Postdocs have already had experience troubleshooting their way through their work in the past, and are expected to be able to leverage that experience by operating more independently. Some projects you work on might be new and higher risk, and some might be stalled and in need of a fresh perspective.
-   In addition, postdocs are strongly encouraged to pursue their own independent research interests along paths related to the work we do. For projects that succeed, they should have "future directions" that a postdoc can take forward into their own, independent careers in the future.
-   Grant writing is a crucial aspect of a postdoc's job. It both funds your position and your research where possible, and most critically, gives you practice and experience seeking and applying for funding opportunities needed for launching into independent faculty positions.
-   Communicating science is extremely important, be it through manuscripts, conference presentations, or workshops. Expect to keep busy presenting the work you do to others, and use the experience to get your name out there and network!
-   Finding your next step is the ultimate goal of your position. For all the roles you have, they should help focus your skillset, your CV, and open future opportunties for you to move onwards and upwards towards where you want to end up in life.  

## Principal Investigator (PI)



# Lab Proceedings

-   [Working remotely](https://github.com/JRaviLab/group/blob/master/docs/howto_work_remotely.md) \| [CU Remote Work Agreement](https://app.smartsheet.com/b/form/f5c5dd3f01dc4eefb3711a4fce6955fe "CU Anschutz Remote Work Agreement")
-   Communication within the group \| [Slack](https://jravilab.slack.com "JRaviLab Slack Workspace") \| In-person/Zoom co-work
-   Research update presentations
-   Giving & receiving constructive feedback

*Links and details to follow.*

# Slack

Since our lab runs on [Slack](https://jravilab.slack.com), let's first get you on there. All our conversations & every last bit of science get done here! :) So, please install this on your desktops (phones) and turn on notifications during working hours, whenever that is!

## Getting started

When you join, please introduce yourself in `#general`. Tell us a little about yourself here --- where you are from, what your interests are, science-wise or otherwise, why you are interested in working with us, and in what capacity you'll be joining us.

I've never used Slack \-- where do I even start? Maybe you can start with the [Slack cheatsheet](https://github.com/JRaviLab/cheatsheets/blob/master/slack-misc/slack-cheatsheet.pdf) and [Keyboard shortcuts](https://slack.com/help/articles/201374536-Slack-keyboard-shortcuts).

## What next?

Next, you can join the different channels to participate in various kinds of conversations with the group --- look at the channel description, check out the pinned messages of the channel, and dive right in! Here are a few examples.

Finally, you will be invited to specific project channels (based on the primary and secondary projects you will be working on). Based on chats with your colleagues, if you'd like to contribute to/give feedback to other projects, feel free to join those channels too.

## Meet the group

You may have briefly spoken to a few group members prior to joining. I urge you to take the first few weeks to introduce yourself to the group members and chat with them (via Slack or over coffee/tea) to find out what they are up to and learn a bit about the lab.

# GitHub

If you haven't already, please create a professional GitHub account (e.g., `jananiravi`) with your full name. Once you pass that along to us, we will add you to the [JRaviLab GitHub organization](https://github.com/jravilab). Also, a neat memorable username will give you the opportunity to host your own webpage (e.g., `jravilab.github.io` or `jananiravi.github.io`). Our group repo is [here](https://github.com/JRaviLab/group/tree/master/meetings).

# Social media

If you have officially joined us as a grad or postdoc, or undergrad for 3/6+ months, you will automatically get added to our [group webpage](https://jravilab.github.io/#people). If not, please check a few sample pages and furnish me with those details -- I can add you there right away. Also, we use Twitter for professional networking & announcements (connecting with the broader scientific/R/technical communities). If you have a Twitter handle, share it with me (DM), or follow #auto-twitter for updates. You can check out/follow a few accounts maintained by us: [JRaviLab](https://twitter.com/jravilab) \| [my handle](https://twitter.com/janani137) \| [RLadies-Aurora](https://twitter.com/rladies-aurora) \| [RLadies-EastLansing](https://twitter.com/rladies-eastlansing) \| [Women+ Data Science](https://twitter.com/womenplusdata) \| [AsiaR](https://twitter.com/AsiaR-comm) \| [ISMB EvolCompGen COSI](https://twitter.com/EvolComp). Thanks to recent *interesting* changes at Twitter, people have been migrating to Mastodon (e.g., [genomic.social](https://genomic.social/explore), [fosstodon](https://fosstodon.org/explore))!

If you would like to co-maintain any of these accounts or our webpage, please DM me. I'm always looking for volunteers! :)
