# Resources

## Funding

We strongly encourage trainees to apply for scholarships/fellowships or other grants to help support their independent research and to get acquainted with the process of developing competitive research and personal statements.

Here are a few scholarship and funding opportunities:

### Grad students

-   [Graduate student funding opportunities (c/o JHU)](https://research.jhu.edu/rdt/funding-opportunities/graduate)

-   [\@CUDenver](https://gs.ucdenver.edu/funding)

-   [NSF GRFP](https://www.cuanschutz.edu/offices/career-development/funding-resources#ac-nsf-grfp-fellowships-0)

-   [NIH F30, F31](https://www.cuanschutz.edu/offices/career-development/funding-resources#ac-nih-nrsa-fellowships-f30-f31-f32-and-k99r00s-1)

-   [Graduate tuition for in-state, out-of-state, non-resident, international students](https://www.cuanschutz.edu/student-finances/tuition-fees/graduate)

-   [Immigrants vs resident aliens](https://highered.colorado.gov/immigrant-or-resident-alien)

#### Training grants

<https://www.cuanschutz.edu/graduate-programs/biomedical-sciences-program/resources/grants-and-fellowships>

#### AWIS

[https://awis.memberclicks.net](https://awis.memberclicks.net/){.uri}

### Undergrads/postbacs

-   [Colorado Biomedical Informatics Summer Training Fellowship for URM](https://www.cuanschutz.edu/docs/librariesprovider233/compbioscience/deadline-extended_sttp-2022-flyer.pdf) Mail Caitlin Moloney with questions: [caitlin.moloney\@cuanschutz.edu](mailto:caitlin.moloney@cuanschutz.edu)

-   [Loan repayment program](https://www.lrp.nih.gov)

-   [University of Colorado Anschutz Medical Campus Preparation in Interdisciplinary Knowledge to Excel (PIKE) PREP](https://medschool.cuanschutz.edu/colorado-cancer-center/education/pike-prep) (URM + citizen + BS in biomedical field)

-   [For high school, undergraduate, and graduate/professional students](https://graduateschool.cuanschutz.edu/programs-of-study/summer-programs)

### Postdocs

-   [Beautiful central resource maintained by JHU](https://research.jhu.edu/rdt/funding-opportunities/postdoctoral/)

-   [Postdoctoral fellowships for international scholars](https://www.cuanschutz.edu/offices/career-development/funding-resources#ac-postdoctoral-fellowships-for-international-scholars-2)

-   [NIH F32, K99/R00](https://www.cuanschutz.edu/offices/career-development/funding-resources#ac-nih-nrsa-fellowships-f30-f31-f32-and-k99r00s-1)

### Other

-   [Anschutz Funding and Fellowships](https://www.cuanschutz.edu/offices/career-development/funding-resources)

-   [Ludeman Center for Women's Health Research](https://medschool.cuanschutz.edu/center-for-womens-health-research/researchers-academics/funding)

## CU resources

### Health and Wellness

CU Anschutz: [Mental health](https://www.cuanschutz.edu/mental-health-resources)\| [Health and Wellness Center](https://anschutzwellness.com)

MSU: [Mental health](https://caps.msu.edu)\| [Student Health & Wellness](https://studenthealth.msu.edu)\| [Fitness](https://healthpromotion.msu.edu/fitness)

### [Women in STEM](https://www.cuanschutz.edu/services/women-in-stem/resources)

### JEDI ⚔️
_Justice, Equity, Diversity, and Inclusion_

-   [Central Office of Diversity, Equity, Inclusion, and Community Engagement](https://www.cuanschutz.edu/offices/diversity-equity-inclusion-community)
-   [Office of Disability, Access, and Inclusion](https://www.cuanschutz.edu/offices/office-of-disability-access-and-inclusion/home-page)
-   [Office of Diversity and Inclusion](https://medschool.cuanschutz.edu/deans-office/diversity-inclusion)
-   [DEI education, outreach, and recruitment](https://medschool.cuanschutz.edu/biochemistry/diversity-equity-inclusion)

## Publication, Authorship & Research Misconduct

### Publishing

To quote the Foreign Secretary of the Royal Society Dr. Mark Walport, ["Science isn't finished until it's communicated."](https://www.climatechangenews.com/2013/10/03/science-is-not-finished-until-its-communicated-uk-chief-scientist/) If work isn't documented, written up, peer-reviewed, and made publicly available, it's no different than if the work hadn't been performed in the first place. For our group, that might involve writing clearly commented, clean code, submitting it for code reviews, and sharing it through GitHub, or it could involve writing a manuscript and submitting it to scientific journals. In any case, it is imperative to work towards sharing [reproducible, repeatable, and replicable science.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5778115/)

### Authorship

It's often said that publications and citations are the [currency of science](https://socialsciences.nature.com/posts/54635-publication-a-universal-currency-in-academia). How does one become an author on a paper? What even is a paper? When is a project ready to publish? Many of these questions are best answered through conversations with peers and collaborators, but there are resources available to help provide context.

-    A paper, a publication, a manuscript, or whatever you might hear it called is a formal write-up of a scientific project. It typically follows a format referred to as [IMRAD](https://en.wikipedia.org/wiki/IMRAD), for Introduction, Methods, Results, and Discussion. These refer to the order of [sections of the paper](https://ori.hhs.gov/content/Chapter-9-Authorship-and-Publication-Responsible-publication), which roughly presents the introduction to the problem or knowledge gap, the methodological approach or techniques the authors decided to use to address the issue established in the introduction, what the results and data outputs of those methods are, and the interpretation of those findings and how they relate back to the problem established at the start. While the exact formatting varies journal-to-journal, this structure generally captures [how scientific results are written and reported.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC442179/)

-    Having your name on a paper's author list typically requires a [substantial intellectual contribution.](https://ori.hhs.gov/content/Chapter-9-Authorship-and-Publication-Authorship) Without your work, the story in the manuscript would not have been complete. Typically, the position of the authors in the list reflects the amount of credit they deserve for the work done, and the PI(s) who oversaw the project receive the last author position(s) to signify that it was their lab(s) who performed the work. Many people make minor contributions that do not make the cut for the author list, and they may earn a space in an Acknowledgements section. Discussions about project responsibilities and the positions contributors will earn on a manuscript should happen early and often. The details of this vary from field-to-field and lab-to-lab, but a good overview can be found [in this article interviewing many different scientists across disciplines.](https://www.science.org/content/article/how-navigate-authorship-scientific-manuscripts)

-    What kinds of contributions are important? Researchers have asked this question enough times to lead to the creation of a framework called [CRediT](https://credit.niso.org/), for Contributor Roles Taxonomy. While this isn't the final say on what types of contributions there can be on a manuscript, many journals have adopted the CRediT system to specifically assign which authors contributed in what ways in a paper, so it's definitely worth a look. 

-   What does it mean if you're an author? No matter your position in the author list, it means you are literally assigning your name to work performed. Even if you only worked on one small part of the analysis, you must be familiar with all aspects of the paper. Your authorship is a statement that you vouch for the content, the methods, and the conclusions made in the paper. While honest mistakes do happen and can slip through to publication, all authors should do their best to ensure everything was conducted to the highest standards for scientific rigor. Mistakes that signficantly change the interpretation or outcome of an experiment, or worse, intentionally misleading or fraudulent data can seriously affect or even end scientific careers for authors on erroneous papers. Authorship should be taken seriously, because contributing to the larger body of scientific knowledge can and does have real impacts on the world and lives in it. 

### Research Misconduct

-   If you are concerned about misconduct by fellow scientists, talk to them first! Science is inherently collaborative and everybody brings a unique perspective -- you may notice something that others have missed, and simply asking about it can course correct a project. If you don't feel satisfied by the answers, or if a researcher is not acting in good faith, it is your responsibility to [report potential misconduct](https://www.colorado.edu/researchinnovation/rcr/research-misconduct). In cases where you aren't certain but still have concerns, you can speak with a Research Integrity Officer at CU and discuss whether the issue qualifies as misconduct before escalating to a formal report. 

### [Writing Center at CU Anschutz](https://clas.ucdenver.edu/writing-center/locations/writing-center-cu-anschutz)
